{
 "title": "Samma.io",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Scanners Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Nikto",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: nikto",
     "timeField": "@timestamp"
    },
    {
     "alias": "Tsunami",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: tsunami",
     "timeField": "@timestamp"
    },
    {
     "alias": "Nmap",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: nmap*",
     "timeField": "@timestamp"
    },
    {
     "alias": "Base",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: base",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tsunami IP Address",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "networkEndpoint.ipAddress.address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "networkEndpoint.ipAddress.address",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "samma-io.scanner: tsunami ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tsunami Ports Find",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "networkEndpoint.port.portNumber",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: tsunami AND networkEndpoint.port.portNumber:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tsunami Software Found",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "software.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "software.name", "id": "1", "type": "cardinality" }
     ],
     "query": "samma-io.scanner: tsunami",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nmap Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "protocol",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: nmap*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nmap Targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "target", "id": "1", "type": "cardinality" }
     ],
     "query": "samma-io.scanner: nmap*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nmap Ports Find",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "port",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "samma-io.scanner: nmap*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recon IP Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "samma-io.scanner",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "IP", "id": "1", "type": "cardinality" }
     ],
     "query": "samma-io.scanner: base ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "A Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "HostName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Type : \" A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nameservers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "HostName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Type : \" NS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PTR Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "HostName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Type : \" PTR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nikto Findings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "finding",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type: Nikto",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nikto Findings / Target",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "target",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "finding", "id": "1", "type": "cardinality" }
     ],
     "query": "_exists_:finding",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nikto Targets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "target",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "target", "id": "1", "type": "cardinality" }
     ],
     "query": "type: Nikto",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nikto OSVDB",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "OSVDB",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type: Nikto",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}